version: "4"
services:
  app:
    build: .
    command: python main.py
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
    env_file: .env

  redis:
    image: redis:6.2
    restart: always
    volumes:
      - tm-redis:/data
    ports:
      - 6379:6379
    expose:
      - "6379"

  db:
      image: "postgres:16-alpine"
      volumes:
        - tm-db:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      expose:
        - "5432"
      ports:
        - 5432:5432

volumes:
  tm-db: null
  tm-redis: null